// Joyn Strategy Hub — seed script
// Run: npm run seed
// Requires .env.local with NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY

const { createClient } = require('@supabase/supabase-js')
require('dotenv').config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

const POSTS = [
  { id:'1',  date:'2026-02-20', platform:'Instagram', format:'Announcement Post',        hook:"We're live. 600 million people have been waiting for this.",                                                                          shoot:'Founder photo or product flat lay on warm Joyn orange surface. This is your launch post — keep it personal and real, not overly produced.',                                                                                                                                                                                          caption:"We're live. 🧡\n\n600 million people have been waiting for this.\n\nJoyn is the first supplement formulated specifically for ALDH2 deficiency — the genetic reason 1 in 3 East Asians (and millions more) turn red when they drink.\n\nWoman-founded. USA-made. Third-party tested.\n\nIf you've ever left a party early, skipped a toast, or felt embarrassed at a happy hour — this is for you.\n\nDrop a 🧡 if you've been waiting for something like this.\n\n#Joyn #ConfidenceInACapsule #ALDH2 #AlcoholFlush #WomanFounded #Launch #NewBrand" },
  { id:'2',  date:'2026-02-21', platform:'TikTok',     format:'Educational Hook',         hook:'Why your face turns red when you drink — the genetic truth nobody told you',                                                              shoot:'Green screen with ALDH2 enzyme diagram. Keep under 60s. This is your hero education post — high save + share rate. It blows up.',                                                                                                                                                                                                  caption:"Why your face turns red when you drink — the genetic truth nobody told you 🧬\n\nIt's called ALDH2 deficiency. 1 in 3 East Asians carry the gene. 600 million people worldwide.\n\nHere's what happens:\n→ You drink alcohol\n→ Your body converts it to acetaldehyde (toxic)\n→ ALDH2 deficiency = your body can't break it down fast enough\n→ Acetaldehyde builds up → redness, racing heart, nausea\n\nThe \"fix\" people use? Pepcid AC. An antacid. Off-label. Damages your stomach.\n\nWe built Joyn — the first supplement designed specifically for ALDH2 deficiency.\n\nDrop \"flush\" in the comments and I'll DM you the link 👇\n\n#ALDH2 #AlcoholFlush #AsianGlow #HealthTok #SupplementTok #GeneticHealth #Joyn" },
  { id:'3',  date:'2026-02-22', platform:'Instagram', format:'Carousel (6 slides)',       hook:'Save this. Share it with someone who needs it. 📌',                                                                                      shoot:'Slide 1: bold hook on Joyn orange bg. Slides 2–5: one ALDH2 fact each on clean white. Slide 6: CTA + discount code.',                                                                                                                                                                                                              caption:"Save this. Share it with someone who needs it. 📌\n\nALDH2 deficiency affects 600 million people — yet most people have never heard of it.\n\n1 in 3 East Asians carry the gene. Millions more across all backgrounds.\n\nFor years, the \"solution\" was Pepcid AC — an antacid, off-label, that damages your stomach.\n\nJoyn is the first supplement formulated specifically for ALDH2 deficiency.\nNot a mask. A real answer for real biology.\n\nWoman-founded. USA-made. Third-party tested.\n\n→ Link in bio 🧡\n\n#ALDH2 #AlcoholFlush #AsianGlow #Joyn #HealthEducation #WomanFounded #ConfidenceInACapsule #AAPI" },
  { id:'4',  date:'2026-02-23', platform:'TikTok',     format:'Relatable List',            hook:'Things people with Asian flush relate to (a thread) 😭',                                                                                shoot:'Text list on screen, trending audio, react to each one. High comment + share format.',                                                                                                                                                                                                                                               caption:"Things people with Asian flush relate to (a thread) 😭\n\n✗ \"One drink and my face looks like a tomato\"\n✗ Googling \"alcohol flush remedy\" for the 100th time\n✗ Ordering club soda at work happy hours\n✗ Leaving parties before the toast\n✗ Taking Pepcid and worrying about your stomach\n✗ Someone asking \"are you OK?\" when you're just having fun\n✗ Skipping champagne at your own celebration\n\nNone of us signed up for this.\nBut now there's actually a real answer.\n\nJoyn — the first supplement formulated for ALDH2.\n\nComment your most relatable one 👇 I read every comment\n\n#AsianGlow #ALDH2 #AlcoholFlush #AsianAmericanProblems #Joyn #FlushReaction" },
  { id:'5',  date:'2026-02-24', platform:'TikTok',     format:'First-Person Story',        hook:"I tried Joyn at my work happy hour and I'm still processing 😭",                                                                       shoot:'Selfie cam. Casual, conversational — sitting in a car or at home. No script.',                                                                                                                                                                                                                                                       caption:"I tried Joyn at my work happy hour and I'm still processing 😭\n\nI've worked at this company for 3 years. I've never had more than one drink at work events.\n\nNot because I don't want to. Because two drinks and my face looks like a fire alarm.\n\nTuesday: took 2 Joyn capsules 30 min before. Had two glasses of wine. Stayed for 2+ hours.\n\nMy manager said \"you seem more relaxed lately.\"\n\nI didn't tell him why. I didn't have to.\n\n#Joyn #WorkHappyHour #ALDH2 #AlcoholFlush #HealthTok #ConfidenceInACapsule" },
  { id:'6',  date:'2026-02-25', platform:'TikTok',     format:'Short Hook',                hook:'Red wine. Not red face. 🍷',                                                                                                             shoot:'Short, punchy — under 20 seconds. B-roll of someone enjoying wine at dinner, looking relaxed.',                                                                                                                                                                                                                                     caption:"Red wine. Not red face. 🍷\n\nThe thing about ALDH2 deficiency is that it's not about how much you drink.\n\nOne glass of rosé and your face betrays you — because your body processes acetaldehyde slower than it should.\n\nJoyn supports ALDH2 enzyme activity so your body can actually do its job.\n\nTwo capsules. Thirty minutes. That's it.\n\nUse code JOYN15 → link in bio 🧡\n\n#Joyn #RedWine #ALDH2 #AlcoholFlush #ConfidenceInACapsule #FlushFree",                         promo_code:'JOYN15' },
  { id:'7',  date:'2026-02-26', platform:'Instagram', format:'Q&A Prompt',                 hook:'Drop your questions about alcohol flush and Joyn below 👇',                                                                             shoot:'Simple post — Joyn orange background or casual founder photo.',                                                                                                                                                                                                                                                                     caption:"Drop your questions about alcohol flush and Joyn below 👇\n\nWe're doing a full Q&A this weekend — no question is too basic, no question is too scientific.\n\nWe want to know:\n→ When did you first notice the flush?\n→ What have you tried before?\n→ What do you want to know about Joyn?\n\nEverything gets answered. Every story gets heard.\n\nThis community is what we built Joyn for. 🧡\n\n#Joyn #QandA #ALDH2 #AlcoholFlush #Community #AskUsAnything" },
  { id:'8',  date:'2026-02-27', platform:'TikTok',     format:'Tier List',                  hook:'Rating every alcohol flush "cure" from worst to best (HONEST)',                                                                         shoot:'On-screen tier list with comedic reaction to each. Fast cuts. Highly shareable.',                                                                                                                                                                                                                                                    caption:"Rating every alcohol flush \"cure\" from worst to best — be honest, you've tried most of these 😅\n\n❌ 5/10 — Cold water on face. Reduces redness for 2 minutes.\n❌ 4/10 — Eating a huge meal first. Slows absorption, doesn't fix flush.\n❌ 3/10 — Antihistamines. Makes you drowsy, doesn't help acetaldehyde.\n⚠️ 2/10 — Pepcid off-label. Masks the symptom, real stomach risks.\n❌ 1/10 — Just stop drinking. OK sure, thanks.\n✅ 9/10 — Joyn. Actually formulated for ALDH2 enzyme activity. First of its kind.\n\nMinus 1 because nothing is perfect and I'm honest.\n\nLink in bio.\n\n#AlcoholFlush #AsianGlow #ALDH2 #Joyn #HealthTok #FlushRemedies" },
  { id:'9',  date:'2026-02-28', platform:'TikTok',     format:'Before / After',             hook:'Before Joyn vs. After Joyn: The honest version 🔄',                                                                                    shoot:'Split screen or alternating text cards. Keep it real and grounded.',                                                                                                                                                                                                                                                                 caption:"Before Joyn vs. After Joyn: The honest version 🔄\n\nBefore:\n→ One drink = watching the clock\n→ Happy hours = sparkling water and excuses\n→ Weddings = the person who left at 9pm\n→ First dates = counting sips\n→ Work events = strategic avoidance\n\nAfter:\n→ The full glass\n→ The second toast\n→ The 1am table at the reception\n→ Actually tasting the wine\n→ Being present for it\n\n600 million people have ALDH2 deficiency. Most of them don't know it yet.\n\nDrop \"flush\" in the comments and I'll DM you the link 👇\n\n#Joyn #BeforeAndAfter #ALDH2 #AlcoholFlush #HealthTok #ConfidenceInACapsule" },
  { id:'10', date:'2026-03-01', platform:'TikTok',     format:'Educational Warning',        hook:"Pepcid for alcohol flush? Your doctor probably doesn't know this 😳",                                                                  shoot:'Calm, credible delivery. Show Reddit thread screenshots as B-roll.',                                                                                                                                                                                                                                                                 caption:"Pepcid for alcohol flush? Your doctor probably doesn't know this 😳\n\nMillions of people use H2 blockers (Pepcid, Zantac) off-label to reduce flush.\n\nHere's the problem:\n→ They block histamine — masking the red face symptom\n→ They DON'T help your body break down acetaldehyde\n→ Long-term: stomach ulcers, reduced acid, dependency\n→ Never tested or approved for this purpose\n\nAnd yet it's the #1 advice on Reddit and TikTok.\n\nJoyn works differently. Supports ALDH2 enzyme activity — so your body actually processes the acetaldehyde instead of just hiding it.\n\nIf this helped, share it. Link in bio 🙏\n\n#AlcoholFlush #Pepcid #ALDH2 #AsianGlow #HealthTok #DrinkingTips #Joyn" },
  { id:'11', date:'2026-03-02', platform:'TikTok',     format:'Lifestyle Story',            hook:'Open bar at a wedding with zero anxiety 💒',                                                                                            shoot:'Cinematic clips from a wedding or a night out — toasts, dancing, being present.',                                                                                                                                                                                                                                                    caption:"Open bar at a wedding with zero anxiety 💒\n\nYou know the wedding mental math:\n→ Getting seated next to people you just met\n→ Champagne toast coming\n→ Choosing between looking rude (not drinking) or turning red (drinking)\n\nThis weekend: Joyn before the ceremony. Open bar, 4+ hours, multiple toasts, dancing.\n\nZero flush. Zero hiding. Zero mental math.\n\nI was just there. Fully.\n\n#Joyn #WeddingSeason #OpenBar #ALDH2 #AlcoholFlush #ConfidenceInACapsule" },
  { id:'12', date:'2026-03-03', platform:'Instagram', format:'Quote Card',                  hook:'"[Customer quote — their own words, their own moment.]" — [Name, Age]',                                                               shoot:'Clean quote card on Joyn orange background. Let the real quote do all the work.',                                                                                                                                                                                                                                                   caption:"\"[Customer quote — their own words, their own moment.]\" — [Name, Age] 🥂\n\n[1–2 sentences: their background. What they struggled with. How long they lived with it.]\n\n[Their Joyn moment — one specific real detail. Real event. Real time. Real feeling.]\n\nThat's why we built this.\n\nReal review. Real customer.\n\n→ Link in bio. Use code [ADD LAUNCH CODE] for 15% off.\n\n#Joyn #CustomerStory #ALDH2 #AlcoholFlush #ConfidenceInACapsule #Testimonial",          warn:'Template post — replace every [placeholder] with a real verified customer before posting. Get explicit written permission. Never post fabricated testimonials.', promo_code:'[ADD LAUNCH CODE]' },
  { id:'13', date:'2026-03-04', platform:'Instagram', format:"Women's History Month",       hook:"Woman-founded. For the 600M who've been hiding. 💛",                                                                                  shoot:"Founder to camera or a clean brand graphic. Women's History Month energy — genuine, not performative. This is your brand story moment.",                                                                                                                                                                                             caption:"Woman-founded. For the 600M who've been hiding. 💛\n\nWomen's History Month isn't about a discount.\nIt's about who built this — and why.\n\nA woman with ALDH2 deficiency. A woman who spent years hiding her face at dinner. A woman who decided the 600 million people being ignored deserved a real solution.\n\nJoyn exists because of that moment.\n\nThis month — celebrate freely.\n\n→ Link in bio. Use code [ADD CODE] for 25% off.\n\n#WomensHistoryMonth #WomanFounded #ALDH2 #AlcoholFlush #Joyn #ConfidenceInACapsule #ForThe600M",    promo_code:'[ADD CODE]' },
  { id:'14', date:'2026-03-05', platform:'Instagram', format:'Spring Season Post',          hook:'Spring is here. So is your confidence. 🌸',                                                                                           shoot:"Bright outdoor aesthetic — patio, first warm day, friends at a rooftop bar. Natural light, that first-day-of-spring energy.",                                                                                                                                                                                                       caption:"Spring is here. So is your confidence. 🌸\n\nPatio season is back.\n\nThe rooftop bars. The afternoon rosé. The \"let's grab a drink outside\" texts.\n\nAnd for the first time — you're showing up fully.\n\nNo counting drinks. No watching your face in the phone camera. No making excuses to leave early.\n\nTwo capsules. Thirty minutes. Enjoy every minute of it.\n\nThis spring is different. 🧡\n\nUse code [ADD CODE] → link in bio\n\n#Joyn #SpringSeason #ALDH2 #AlcoholFlush #ConfidenceInACapsule #PatioSeason",              promo_code:'[ADD CODE]' },
  { id:'15', date:'2026-03-06', platform:'TikTok',     format:'Expert Review',              hook:"Asked a doctor to review Joyn — here's what she said 🩺",                                                                              shoot:'Credible, calm delivery to camera. Do NOT be salesy — let the science speak.',                                                                                                                                                                                                                                                      caption:"Asked a doctor to review Joyn — here's what she said 🩺\n\nWe sent our full formula to [Dr. Name, Credentials — e.g. \"Dr. Jane Park, MD, metabolic health\"].\n\nHer response:\n\n\"[Direct quote — her own words. Get written approval before publishing.]\"\n\nWe're not a drug. We're not medical advice. But we are built on real science.\n\nFull formula breakdown → link in bio 🔬\n\n#Joyn #DoctorReview #ALDH2 #HealthTok #SupplementTok #Science #AlcoholFlush",              warn:"Template post — replace with a real medical advisor's actual words. Get written sign-off before publishing. Never fabricate expert endorsements — this is an FTC violation." },
  { id:'16', date:'2026-03-07', platform:'Instagram', format:'Carousel (6 slides)',         hook:'ALDH2 deficiency — the complete breakdown 🧬',                                                                                          shoot:'Clean educational carousel. White + orange palette. Save rate will be high.',                                                                                                                                                                                                                                                        caption:"ALDH2 deficiency — the complete breakdown 🧬\n\nSave this. Share it with someone who's been told \"just take Pepcid.\"\n\nHere's everything your doctor probably never told you:\n\n→ What ALDH2 is and why it matters\n→ Why 1 in 3 East Asians carry the gene\n→ What actually happens in your body when you flush\n→ Why Pepcid is the wrong answer\n→ What Joyn does differently\n\n600 million people deserve to understand their own biology.\n\n→ Link in bio 🧡\n\n#ALDH2 #AlcoholFlush #AsianGlow #HealthEducation #Joyn #ConfidenceInACapsule #SaveThis" },
  { id:'17', date:'2026-03-08', platform:'TikTok',     format:"International Women's Day",  hook:"International Women's Day. This one is personal.",                                                                                    shoot:"Founder to camera. No script, no teleprompter. Just talk. IWD is a natural moment to tell the founder story — don't over-produce this, authenticity converts.",                                                                                                                                                                    caption:"International Women's Day. This one is personal. 💛\n\nI built Joyn because I was tired of hiding.\n\nEvery networking event: sparkling water, hoping nobody noticed.\nEvery wedding toast: a sip and then back to water.\nEvery first date: counting drinks, watching my face.\n\nThen I learned it was genetic. ALDH2 deficiency. Not just me — 600 million people.\n\nI became obsessed with a real solution. Not Pepcid. Not gimmicks.\n\nYears of development. USA-made. Third-party tested. Woman-founded.\n\nThis is Joyn. For every woman who's ever hidden at the table. 💛\n\n#IWD2026 #InternationalWomensDay #WomanFounded #ALDH2 #AlcoholFlush #Joyn #ConfidenceInACapsule" },
  { id:'18', date:'2026-03-09', platform:'Instagram', format:'Story Poll',                  hook:'What celebration are you most excited for this year?',                                                                                  shoot:'Post a Story with a poll sticker. Joyn orange background.',                                                                                                                                                                                                                                                                         caption:"What celebration are you most excited for this year? 🎉\n\nDrop it in the comments or vote in our story poll 👆\n\nWhether it's a wedding, a birthday, a work win, or just a Friday night that finally feels like something —\n\nYou deserve to be fully present for all of it.\n\nJoyn is here for every single one. 🧡\n\n#Joyn #Celebrate #ALDH2 #ConfidenceInACapsule #CelebrateFreely" },
  { id:'19', date:'2026-03-10', platform:'TikTok',     format:'Selfie Diary',               hook:"7 days with Joyn — I'm going to be honest",                                                                                            shoot:'Selfie-cam across 7 real days. Natural lighting. No script. This format converts — authentic > polished.',                                                                                                                                                                                                                                    caption:"7 days with Joyn — I'm going to be honest 📔\n\nDay 1: Took 2 capsules 30 min before drinks. Less flushing than normal. Cautiously optimistic.\n\nDay 2: Work happy hour. Stayed the whole time. Ordered a second drink. My coworker asked why I seemed more relaxed.\n\nDay 4: Date night. Ordered wine without the usual anxiety.\n\nDay 5: Checked my face mid-meal. Normal color. Actually stayed at dinner.\n\nDay 7: I cried a little honestly. 15 years of hiding. 7 days.\n\nNot an ad. Just someone who needed this to exist.\n\n#Joyn #AlcoholFlush #ALDH2 #HealthTok #HonestReview #7DayChallenge #ConfidenceInACapsule" },
  { id:'20', date:'2026-03-11', platform:'Instagram', format:'Founder Feed Post',           hook:"We didn't build Joyn to get rich. We built it because we were tired of hiding.",                                                      shoot:'Personal editorial photo of Brynn or the team. Warm lighting. No product in frame.',                                                                                                                                                                                                                                                caption:"We didn't build Joyn to get rich. We built it because we were tired of hiding. 🍷\n\nTired of showing up to celebrations and quietly managing our faces instead of being present.\n\nTired of the Reddit threads saying \"just take Pepcid.\"\n\nTired of a market full of \"hangover cures\" that weren't built for us at all.\n\n600 million people deserve a real answer. So we built one.\n\nWoman-founded. USA-made. Formulated for your biology, not against it.\n\nJoyn. Confidence in a capsule. 🧡\n\n#Joyn #WomanFounded #ALDH2 #AlcoholFlush #ConfidenceInACapsule #USAMade" },
  { id:'21', date:'2026-03-12', platform:'TikTok',     format:'Lifestyle Video',            hook:'Spring break. No flush edition. 🌴',                                                                                                    shoot:'Fun, energetic spring break energy. Trending audio. Light and summery edit.',                                                                                                                                                                                                                                                        caption:"Spring break is almost here and for the first time you don't have to choose between having fun and hiding your face 🌴\n\nNo more watching your phone camera to check how red you are.\nNo more quietly switching to water after one drink.\nNo more leaving early.\n\nSpring 2026: you're going. You're staying. You're present.\n\nTwo capsules. Thirty minutes. That's it.\n\nUse code [ADD CODE] for 15% off → link in bio 🧡\n\n#SpringBreak #AlcoholFlush #ALDH2 #AsianGlow #Joyn #CelebrateFully #ConfidenceInACapsule",  promo_code:'[ADD CODE]' },
  { id:'22', date:'2026-03-13', platform:'Instagram', format:'Community Spotlight',         hook:"You sent us your stories this month. We can't stop reading them. 🧡",                                                                  shoot:'Collage of real DM screenshots (with permission) or quote cards on Joyn cream background.',                                                                                                                                                                                                                                         caption:"You sent us your stories this month. We can't stop reading them. 🧡\n\n\"[Customer quote 1]\" — [Name, Age or anonymous]\n\n\"[Customer quote 2]\" — [Name, Age or anonymous]\n\n\"[Customer quote 3]\" — [Name, Age or anonymous]\n\n\"[Customer quote 4]\" — [Name or anonymous]\n\nThis is why we built Joyn. Not for the product — for these moments.\n\nKeep sending them. We read every single one.\n\n#Joyn #CommunityStories #ALDH2 #AlcoholFlush #ConfidenceInACapsule #CustomerLove",           warn:'Template post — collect real DM stories before building this. Post an Instagram Story asking followers to share their Joyn moment. Get explicit written permission from each person. Then replace every [placeholder] below.' },
  { id:'23', date:'2026-03-14', platform:'TikTok',     format:'Ingredient Breakdown',       hook:"Every ingredient in Joyn and exactly why it's there 🔬",                                                                               shoot:'Green screen or text overlay with ingredient list. Credible, educational tone.',                                                                                                                                                                                                                                                      caption:"Every ingredient in Joyn and exactly why it's there 🔬\n\nWe're not hiding anything. Let's go through it:\n\n→ Dihydromyricetin (DHM): Studied for supporting alcohol metabolism\n→ NAC: Precursor to glutathione, your body's master antioxidant\n→ B-vitamins: Support liver metabolic function\n→ Milk Thistle: Liver support, used in wellness for centuries\n→ Vitamin C: Antioxidant support during oxidative stress\n\nNo proprietary blends. No \"natural flavors.\" No hiding behind vague labels.\n\nThis is what flush-free actually looks like at the molecular level.\n\nSave this. Full breakdown → link in bio.\n\n#Joyn #Ingredients #ALDH2 #HealthTok #SupplementTok #Transparency #CleanSupplements" },
  { id:'24', date:'2026-03-15', platform:'Instagram', format:'Milestone Post',              hook:'Four weeks in. Thousands of celebrations. 🥂',                                                                                          shoot:'Celebratory and warm. Founder photo, product shot, or a collage of customer moments. This is your mid-month milestone — make it meaningful.',                                                                                                                                                                                       caption:"Four weeks in. Thousands of celebrations. 🥂\n\nWhen we launched, we hoped people would find us.\nWe didn't know they'd find us this fast.\n\nThe stories in our DMs. The reviews. The people saying they finally went to their office party, finally stayed at the wedding, finally had a glass of wine on a first date without counting their heartbeats.\n\nWe built Joyn for the 600 million people with ALDH2 deficiency who've been ignored.\n\nFour weeks done. We're just getting started.\n\nThank you. 🧡\n\n#Joyn #FourWeeks #ALDH2 #AlcoholFlush #ConfidenceInACapsule #ThankYou #WomanFounded" },
  { id:'25', date:'2026-03-16', platform:'TikTok',     format:'Skeptic Response',           hook:"I read every skeptical comment about Joyn so you don't have to 😅",                                                                    shoot:'Fast cuts, text overlay for each objection. Honest and slightly funny.',                                                                                                                                                                                                                                                             caption:"I read every skeptical comment about Joyn so you don't have to 😅\n\n\"It's just a placebo.\" — The enzyme science disagrees. Look up DHM and ALDH2.\n\n\"Just drink less.\" — The point is choice. Not abstinence.\n\n\"Pepcid works fine.\" — Long-term: stomach ulcers, acid dependency. Not fine.\n\n\"Too expensive.\" — One bottle = one month. Calculate your current Pepcid habit.\n\n\"Nothing works for flush.\" — That's what we thought too.\n\nThe skepticism is valid. We earned it by being honest about the science.\n\nFormula transparency → link in bio 🔬\n\n#Joyn #SkepticsWelcome #ALDH2 #HealthTok #AlcoholFlush #ConfidenceInACapsule" },
  { id:'26', date:'2026-03-17', platform:'Instagram', format:"St. Patrick's Day Post",      hook:"St. Patrick's Day without the red face 🍀",                                                                                            shoot:"Green aesthetic with Joyn orange accents. Pint glasses, shamrocks, celebration energy. High-engagement holiday — post early.",                                                                                                                                                                                                      caption:"St. Patrick's Day without the red face 🍀\n\nThe one holiday built entirely around drinking.\n\nAnd for 600 million people — the one holiday that used to feel like the most visible version of their condition.\n\nNot this year.\n\nTwo capsules. Thirty minutes. Wear the green.\n\nHappy St. Patrick's Day from Joyn 🧡\n\n→ Link in bio. Use code [ADD CODE] for 25% off.\n\n#StPatricksDay #Joyn #ALDH2 #AlcoholFlush #ConfidenceInACapsule #CelebrateFreely",          promo_code:'[ADD CODE]' },
  { id:'27', date:'2026-03-18', platform:'TikTok',     format:'Entertainment',              hook:"Rating celebrity flush moments they definitely didn't want us to see 😭",                                                               shoot:'Entertaining — use publicly available footage or general B-roll. Do NOT name specific individuals without legal review first.',                                                                                                                                                                                                      caption:"Rating celebrity flush moments they definitely didn't want us to see 😭\n\n(Solidarity, not mockery — ALDH2 affects everyone regardless of fame or following)\n\n⭐ That awards show toast where someone's face told a whole other story\n⭐ Every red carpet open bar moment caught in 4K... front row... cameras everywhere\n⭐ The group photo at the after-party that lives rent-free in their heads\n\nThe difference between them and you: they had stylists, PRs, and makeup artists on standby.\n\nYou just have Joyn.\n\nCode [ADD CODE] → link in bio 🧡\n\n#Joyn #AsianGlow #ALDH2 #TikTokFun #AlcoholFlush #ConfidenceInACapsule #AsianAmerican",            promo_code:'[ADD CODE]' },
  { id:'28', date:'2026-03-19', platform:'Instagram', format:'Month Wrap-up',               hook:"Month one is a wrap. Here's to the 600M. 🥂",                                                                                           shoot:'Most important post of the month. Emotional, warm. Founder or team photo. Real, personal, not polished. This is the closer.',                                                                                                                                                                                                       caption:"Month one is a wrap. Here's to the 600M. 🥂\n\nWe launched a supplement nobody asked us to build — because we needed it ourselves.\n\nIn four weeks:\n→ Thousands of orders shipped\n→ Hundreds of stories in our DMs\n→ A community we didn't know we were building\n\nFor the person who found us at 2am after a bad night at a dinner party —\nFor the person who shared us with their college roommate —\nFor the person who finally stayed until the last dance —\n\nWe built this for you.\n\nMore is coming. Bring your celebrations.\n\nJoyn. Confidence in a capsule. 🧡\n\n#Joyn #OneMonth #ALDH2 #AlcoholFlush #ConfidenceInACapsule #ThankYou #WomanFounded #USAMade" },
]

async function seed() {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
    console.error('❌ Missing NEXT_PUBLIC_SUPABASE_URL in .env.local')
    process.exit(1)
  }

  console.log('🌱 Seeding Joyn posts...')

  // Check if posts already exist
  const { data: existing } = await supabase.from('posts').select('id').limit(1)
  if (existing && existing.length > 0) {
    console.log('⚠️  Posts already exist. Run with --force to overwrite.')
    if (!process.argv.includes('--force')) process.exit(0)
    await supabase.from('posts').delete().neq('id', '')
    console.log('🗑️  Cleared existing posts.')
  }

  const rows = POSTS.map(p => ({
    id: p.id,
    date: p.date,
    platform: p.platform,
    format: p.format,
    hook: p.hook,
    shoot: p.shoot,
    caption: p.caption,
    warn: p.warn ?? null,
    promo_code: p.promo_code ?? null,
    is_posted: false,
    note: '',
  }))

  const { error } = await supabase.from('posts').insert(rows)
  if (error) { console.error('❌ Seed failed:', error.message); process.exit(1) }

  console.log(`✅ Seeded ${rows.length} posts successfully!`)
}

seed()
